files: ./spec/**/*.cr
run: crystal spec %file% --error-trace -d
---
files: ./src/**/*.cr
run: crystal spec --error-trace -d
---
files: ./shard.yml
run: shards install
---
files: ./README.md
run: crystal docs
